version: "3"

services:
  app:
    build: .
    volumes:
      - .:/app
    command:
      - poetry
      - run
      - python
      - -m
      - argmining_clustering
      - "microtexts/*.json"
      - "essays/*.ann"
